modLoader="javafml"
loaderVersion="[44,)"
issueTrackerURL="https://github.com/Mrbysco/RogueLite-Storage/issues"
license="MIT"

[[mods]]
modId="roguelitestorage"
version="${file.jarVersion}"
displayName="Roguelite Storage"
displayURL="https://www.curseforge.com/minecraft/mc-mods/roguelite-storage"
authors="Mrbysco"
description='''
RogueLite Storage progression solution for hardcore packs
'''
[[dependencies.roguelitestorage]]
modId="minecraft"
mandatory=true
versionRange="[1.19.3,1.20)"
ordering="NONE"
side="BOTH"