modLoader="javafml"
loaderVersion="[40,)"
#issueTrackerURL="https://github.com/Mrbysco/flatterentities"
license="MIT"

[[mods]]
modId="roguelitestorage"
version="${file.jarVersion}"
displayName="Roguelite Storage"
#displayURL="https://www.curseforge.com/minecraft/mc-mods/"
authors="Mrbysco"
description='''
RogueLite Storage progression solution for hardcore packs
'''
[[dependencies.roguelitestorage]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,1.19)"
ordering="NONE"
side="BOTH"