modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/Mrbysco/RogueLite-Storage/issues"
license="MIT"

[[mods]]
modId="roguelitestorage"
version="${file.jarVersion}"
displayName="Roguelite Storage"
displayURL="https://www.curseforge.com/minecraft/mc-mods/roguelite-storage"
authors="Mrbysco"
description='''
RogueLite Storage progression solution for hardcore packs
'''
[[dependencies.roguelitestorage]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.roguelitestorage]]
modId="neoforge"
type="REQUIRED"
versionRange="[20.4.60-beta,)"
ordering="NONE"
side="BOTH"